### PR TITLE
Made the 'safety guaranteed' section functional. Closes #86

### LINKED ISSUE #86: Make the safety guaranteed on landing page functional
**Describe the bug**
Make the safety guaranteed on landing page functional

**Expected behavior**
on hovering on safety guaranteed, we should be able to see the corresponding content

**Screenshots**
image

**Additional context**
here is the [figma link ](https://www.figma.com/design/Tnep6rHkErd8BrVc5Rk4R6/HTML-CSS-Design?node-id=5-726&t=7LQ2UgAkRAlUvSwg-0) for reference

### PR DESCRIPTION
**Pull request by Akshat1276**
Closes #86 

### Type of Change
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
Made the 'safety guaranteed' section functional.

### Implementation Details  
When we hover over the "Safety Guaranteed" box, it will show the corresponding content.

### Demo  
https://github.com/user-attachments/assets/97a5a7a1-0240-4a1a-a03e-334a3ec3b36e

### CODE REVIEW

**Review by Yash-g2310 — COMMENTED** [review]
@Akshat1276 

https://github.com/user-attachments/assets/883a4ca4-493c-4aef-9d5e-b247ce97b8c2

here as you can see when i open a safety guaranteed and hover to it's description (the black div that pops out) , It gets closed automatically,
it would be really beneficial if the selected safety guaranteed closes when i hover out of the combined area of safety guaranteed and it's description
please make the changes,
if you are unable to understand please let me know

**Comment by Akshat1276** [comment]
@Yash-g2310  Sir i understand the change you want. I tried thinking up of some solution, but it did not work. Could you please guide me a bit here, or maybe share some resources from where i can learn and implement the changes. 
image
I tried changing highlighted part in the image, but it didn't work, and I wasn't able to find anything relevant on the internet too. I'll be very grateful if you could guide me a bit here.
Thank you sit

**Comment by Akshat1276** [comment]
@Yash-g2310 Made the advised changes. Please check and merge. 
Thank You

File: resources/javascript/SafetyGuaranteed.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+    safetyBox3.addEventListener("mouseover", function () {
+        if (!safetyItems[i].classList.contains("active")) {
+            safetyItems[i].classList.add("active");
+        }
+    });
+
+    safetyDivItems.addEventListener("mouseover", function () {
+        if (!safetyItems[i].classList.contains("active")) {
+            safetyItems[i].classList.add("active");
```
Comment (Yash-g2310) [inline resources/javascript/SafetyGuaranteed.js:16]: i don't think there is a use of this piece of code, please check

File: resources/css/landingpage.css [hunk 2]
```diff
@@ -245,11 +241,28 @@ nav {
...
     background: rgba(31, 36, 32, 0.9);
+    overflow: hidden;
+    transition: max-height 0.3s ease-in-out;
+    flex-grow: 1;
+    font-size: 26px;
+    display: flex;
+    flex-direction: column;
+    justify-content: center;
+    overflow-wrap: break-word;
+    font-family: "Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS", sans-serif;
```
Comment (Yash-g2310) [inline resources/css/landingpage.css:256]: font family is different in figma

**Review by Yash-g2310 — CHANGES_REQUESTED** [review]
@Akshat1276 i have mentioned some changes please check
also
image
see this image, there is some issue in responsiveness also correct it

File: resources/javascript/SafetyGuaranteed.js (hunk 1 above)
Comment (Akshat1276) [reply resources/javascript/SafetyGuaranteed.js:16]: Yes. I apologize, I will remove it.

File: resources/css/landingpage.css (hunk 2 above)
Comment (Akshat1276) [reply resources/css/landingpage.css]: fixed

**Comment by Yash-g2310** [comment]
@Akshat1276  please fix the responsiveness problem as well

image

**Comment by Akshat1276** [comment]
@Yash-g2310 Sir I matched the dimensions and magnification as per the screenshot attached by you, but in my system, the site looks responsive
image

**Comment by Yash-g2310** [comment]
then it might be an issue from my side, 
The commits are good we would be merging it soon
